export PATH="$HOME/.rbenv/bin:/home/maarten/.rbenv/shims:$PATH"
alias gs="git status"
alias gb="git branch"
alias gd="git diff"
alias gm="git commit"
alias gco="git checkout"
alias b="bundle exec"
alias bi="bundle install"
